# Generated by Django 5.2.7 on 2025-12-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.TextField(default='', help_text='Qor dose kasta'),
        ),
    ]
