# Generated by Django 5.2.7 on 2025-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/images/', verbose_name='Profile Image'),
        ),
    ]
