# Generated by Django 5.2.7 on 2026-01-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_prescription_medicines_medicine_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.TextField(),
        ),
    ]
