# Generated by Django 5.2.7 on 2026-01-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.TextField(default='', help_text='Qor dose kasta'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(default=1, help_text='Qor dawooyinka, kuna kala sooc comma (,)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
