# Generated by Django 6.0 on 2026-01-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_prescription_medicine_prescription_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
    ]
