# Generated by Django 5.2.7 on 2026-01-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_medicine_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.medicine'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(blank=True, help_text='Qor dawooyinka, kuna kala sooc comma (,)', null=True),
        ),
    ]
